# Generated by Django 3.1.7 on 2021-04-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210424_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.seller'),
            preserve_default=False,
        ),
    ]
