# Generated by Django 3.1.7 on 2021-04-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sellerid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.seller'),
            preserve_default=False,
        ),
    ]
