# Generated by Django 3.1.7 on 2021-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20210425_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='model',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='price',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
