# Generated by Django 3.1.7 on 2021-04-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20210425_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
    ]
