# Generated by Django 3.2 on 2021-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_customer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('TV & Appliances', 'TV & Appliances'), ('Men', 'Men'), ('Women', 'Women'), ('Baby & Kids', 'Baby & Kids'), ('Computers', 'Computers'), ('Phones & Tablets', 'Phones & Tablets'), ('Books', 'Books'), ('Accessories', 'Accessories'), ('Others', 'Others'), ('More', 'More')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('0', 'All Season'), ('1', 'Spring 1 March'), ('2', 'Summer 1 June'), ('3', 'Autumn 1 September'), ('4', 'Winter 1 December')], max_length=20),
        ),
    ]
