# Generated by Django 3.2 on 2021-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20210427_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('0', 'None'), ('1', 'New Arrivals'), ('2', 'Trending'), ('3', 'Sales'), ('4', 'Regular Use'), ('5', 'Party Wear'), ('6', 'Ethnic Wear')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Electronics', (('Washing Machine', 'Washing Machine'), ('Refrigerators', 'Refrigerators'), ('Mixer Grinder & Juicer', 'Mixer Grinder & Juicer'), ('Others', 'Others'))), ('TV & Appliances', (('LCD', 'LCD TV'), ('LED', 'LED TV'), ('LEDSmart', 'LED Smart TV'), ('Others', 'Others'))), ('Men', (('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'))), ('Women', (('Saree', 'Saree'), ('Jeans', 'Jeans'), ('Tops', 'Tops'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'))), ('Kids', (('0', 'clothes for upto 2yrs kids'), ('1', 'clothes for upto 5yrs kids'), ('2', 'clothes for upto 10yrs kids'), ('3', 'clothes for upto 15yrs kids'), ('4', 'clothes for above 15yrs kids'))), ('Computers', (('PC', 'PC'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories'), ('Others', 'Others'))), ('Phones & Tablets', (('0', 'Bar Phones'), ('1', 'Smartphones'), ('2', 'Smart Tablets'), ('3', 'Others'))), ('Books', (('Literature', 'Literature'), ('Comics', 'Comics'), ('Story', 'Story'), ('Biography', 'Biography'), ('Educational', 'Educational'), ('Others', 'Others'))), ('Accessories', (('PC', 'PC'), ('Laptops', 'Laptops'), ('Phones', 'Phones'), ('Others', 'Others'))), ('Others', 'Others')], max_length=100),
        ),
    ]
