# Generated by Django 3.2 on 2021-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20210427_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='date',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='customer',
            name='delievery_address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gstinfo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='permanent_address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status1',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('1', 'Shipped'), ('2', 'Out For Delivery'), ('3', 'Arrived'), ('9', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('1', 'Shipped'), ('2', 'Out For Delivery'), ('3', 'Arrived'), ('9', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status3',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('1', 'Shipped'), ('2', 'Out For Delivery'), ('3', 'Arrived'), ('9', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status4',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('1', 'Shipped'), ('2', 'Out For Delivery'), ('3', 'Arrived'), ('9', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='category',
            field=models.CharField(choices=[('Wholesaler', 'Wholesaler'), ('Distributer', 'Distributer'), ('Retailer', 'Retailer'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subcategory',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('TV & Appliances', 'TV & Appliances'), ('Men', 'Men'), ('Women', 'Women'), ('Baby & Kids', 'Baby & Kids'), ('Computers', 'Computers'), ('Phones & Tablets', 'Phones & Tablets'), ('Books', 'Books'), ('Accessories', 'Accessories'), ('Others', 'Others')], max_length=100),
        ),
    ]
